import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
// import OCConnectWrapper from '@/app/components/OCConnectorWrapper';
import { ReactQueryProvider } from "@/app/components/ReactQueryProvider";
import { WalletProvider } from "@/app/components/WalletProvider";
import { Toaster } from "@/app/components/ui/toaster";
import { WrongNetworkAlert } from "@/app/components/WrongNetworkAlert";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Quest Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const opts = {
    redirectUri: 'https://quest-flow-two.vercel.app/redirect', // Adjust this URL
    referralCode: 'PARTNER6', // Assign partner code
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletProvider>
          <ReactQueryProvider>


            {/* <OCConnectWrapper opts={opts} sandboxMode={true}> */}
            <Navbar />
            {children}
            {/* </OCConnectWrapper> */}
            <WrongNetworkAlert />

            <Toaster />
          </ReactQueryProvider>

        </WalletProvider>
      </body>
    </html>
  );
}
